# Bronze
Dado armazenado da mesma maneira que foi extraído

In [52]:
import pandas as pd

bronze = pd.read_excel("data/pedidos_metalurgica_mezzalira.xlsx")
bronze

,Pedido,Data,Cliente,Cidade,Produto,Valor (R$)
0,1001.0,2026-01-01,Irrigação Vale Forte,Petrolina,"Tubo galvanizado 2""",3260
1,1002.0,2026-01-02 00:00:00,Grades Caruaru,Caruaru,"Barra chata 1""",3570
2,1003.0,2026-01-06 00:00:00,Serralheria Capibaribe,recife,Telha trapezoidal,1940
3,1004.0,2026-01-07 00:00:00,Serralheria Capibaribe,Recife,Chapa de aço 3 mm,4910
4,1005.0,2026-01-16,Agro Estruturas São Francisco,Petrolina,Perfil U enrijecido,4500
5,1006.0,2026-01-27,Irrigação Vale Forte,Petrolina,"Cantoneira 1/2""",1350
6,1007.0,01-fev-2026,Grades Caruaru,Caruaru,Perfil U enrijecido,5360
7,1008.0,2026-02-04 00:00:00,Estaleiro Porto Novo,REC,"Cantoneira 1/2""",3900
8,1009.0,2026-02-06 00:00:00,Serralheria Capibaribe,Recife,"Barra chata 1""",4040
9,1010.0,2026-02-07 00:00:00,Calhas Olinda,Olinda,"Tubo galvanizado 2""",5700
10,1011.0,2026-02-13 00:00:00,Calhas Olinda,Olinda,Chapa de aço 3 mm,4400
11,1012.0,2026-02-15 00:00:00,Grades Caruaru,Caruaru,"Tubo galvanizado 2""",4510
12,1013.0,2026-02-16 00:00:00,Estaleiro Porto Novo,Recife,Perfil U enrijecido,2410
13,1014.0,2026-02-17 00:00:00,Agro Estruturas São Francisco,Petrolina,"Barra chata 1""","R$ 630,00"
14,NaN,NaN,NaN,NaN,NaN,NaN
15,1015.0,2026-02-19,Grades Caruaru,Caruaru,Perfil U enrijecido,5160
16,1016.0,2026-02-20 00:00:00,Serralheria Capibaribe,REC,"Cantoneira 1/2""",2390
17,1017.0,2026-02-23 00:00:00,Estruturas Piedade,Jaboatão dos Guararapes,Telha trapezoidal,3920
18,1018.0,2026-02-25 00:00:00,Agro Estruturas São Francisco,Petrolina,Telha trapezoidal,3340
19,1019.0,2026-02-26,Serralheria Capibaribe,recife,Chapa de aço 3 mm,"R$ 2.240,00"
20,1020.0,2026-02-26 00:00:00,Construtora Boa Vista,Recife,"Cantoneira 1/2""",1260
21,1021.0,2026-02-27,Irrigação Vale Forte,Petrolina,Telha trapezoidal,4800
22,1022.0,2026-03-05,Estruturas Piedade,Jaboatão dos Guararapes,"Barra chata 1""",2980
23,1015.0,2026-02-19,Grades Caruaru,Caruaru,Perfil U enrijecido,5160
24,1023.0,2026-03-05 00:00:00,Metalfer Agreste,Caruaru,"Barra chata 1""",5960
25,1024.0,2026-03-06 00:00:00,Irrigação Vale Forte,Petrolina,Chapa de aço 3 mm,1590
26,1025.0,06-mar-2026,Serralheria Capibaribe,REC,Chapa de aço 3 mm,"R$ 2.140,00"
27,1026.0,2026-03-07 00:00:00,Esquadrias Recife Antigo,Recife,"Tubo galvanizado 2""","R$ 5.480,00"
28,1027.0,2026-03-10 00:00:00,Metalfer Agreste,Caruaru,"Cantoneira 1/2""",440
29,1028.0,2026-03-12 00:00:00,Indústria Guararapes,Jaboatão dos Guararapes,Perfil U enrijecido,4290
30,1029.0,12-mar-2026,Estaleiro Porto Novo,REC,Perfil U enrijecido,"R$ 6.190,00"
31,1027.0,2026-03-10 00:00:00,Metalfer Agreste,Caruaru,"Cantoneira 1/2""",440
32,1030.0,2026-03-12 00:00:00,Metalfer Agreste,Caruaru,Chapa de aço 3 mm,1220
33,NaN,NaN,NaN,NaN,NaN,NaN
34,1023.0,2026-03-05 00:00:00,Metalfer Agreste,Caruaru,"Barra chata 1""",5960
35,1031.0,2026-03-14,Estaleiro Porto Novo,recife,Perfil U enrijecido,2080
36,1032.0,2026-03-14,Indústria Guararapes,Jaboatão dos Guararapes,"Barra chata 1""",800
37,1033.0,2026-03-15 00:00:00,Construtora Boa Vista,recife,Chapa de aço 3 mm,3340
38,1034.0,15-mar-2026,Grades Caruaru,Caruaru,Chapa de aço 3 mm,4510
39,1035.0,2026-03-16 00:00:00,Indústria Guararapes,Jaboatão dos Guararapes,"Cantoneira 1/2""",1650
40,1036.0,2026-03-16 00:00:00,Estruturas Piedade,Jaboatão dos Guararapes,Chapa de aço 3 mm,5350
41,1037.0,19-mar-2026,Calhas Olinda,Olinda,"Tubo galvanizado 2""",5040
42,1038.0,2026-03-20 00:00:00,Grades Caruaru,Caruaru,"Cantoneira 1/2""","R$ 5.480,00"
43,1039.0,20-mar-2026,Serralheria Alto da Sé,Olinda,Chapa de aço 3 mm,930
44,1040.0,2026-03-20 00:00:00,Calhas Olinda,Olinda,Telha trapezoidal,410
45,1041.0,2026-03-21,Calhas Olinda,Olinda,"Barra chata 1""",1330
46,1042.0,2026-03-22 00:00:00,Indústria Guararapes,Jaboatão dos Guararapes,"Cantoneira 1/2""",3950
47,1043.0,2026-03-25 00:00:00,Estaleiro Porto Novo,Recife,Telha trapezoidal,5540
48,1044.0,2026-03-26 00:00:00,Indústria Guararapes,Jaboatão dos Guararapes,Telha trapezoidal,3800
49,1045.0,2026-03-27 00:00:00,Estaleiro Porto Novo,recife,Telha trapezoidal,"R$ 4.960,00"
50,1046.0,2026-04-01 00:00:00,Indústria Guararapes,Jaboatão dos Guararapes,"Barra chata 1""",1120
51,NaN,NaN,NaN,NaN,NaN,NaN
52,1047.0,2026-04-05 00:00:00,Metalfer Agreste,Caruaru,"Tubo galvanizado 2""",5890
53,1048.0,2026-04-10 00:00:00,Calhas Olinda,Olinda,"Tubo galvanizado 2""",5770
54,1049.0,2026-04-13,Calhas Olinda,Olinda,"Cantoneira 1/2""",4470
55,1050.0,2026-04-20 00:00:00,Calhas Olinda,Olinda,Telha trapezoidal,950
56,1051.0,2026-04-23 00:00:00,Grades Caruaru,Caruaru,Chapa de aço 3 mm,1040
57,1052.0,2026-04-23 00:00:00,Esquadrias Recife Antigo,REC,Perfil U enrijecido,2440
58,1053.0,2026-04-26 00:00:00,Irrigação Vale Forte,Petrolina,Telha trapezoidal,3610
59,1047.0,2026-04-05 00:00:00,Metalfer Agreste,Caruaru,"Tubo galvanizado 2""",5890

# Logger

In [53]:
logs = []
def logger(o_que_encontrei, o_que_fiz, linhas_afetadas, justificativa=""):
    logs.append({
        "O que encontrei": o_que_encontrei,
        "O que fiz": o_que_fiz,
        "Linhas afetadas": int(linhas_afetadas),
        "Justificativa (se houve dúvida)": justificativa,
    })
    print(f"✔ {o_que_encontrei}: {linhas_afetadas} linha(s) afetada(s)")

# Prata
Correções e manipulações dos dados

In [54]:
prata = bronze.copy()

columnsNames = bronze.columns.tolist()
for column in columnsNames[1:]:
    print("\n"+column+"\n")
    for valor in prata[column].unique():
        print(valor)

Data

2026-01-01
2026-01-02 00:00:00
2026-01-06 00:00:00
2026-01-07 00:00:00
2026-01-16
2026-01-27
01-fev-2026
2026-02-04 00:00:00
2026-02-06 00:00:00
2026-02-07 00:00:00
2026-02-13 00:00:00
2026-02-15 00:00:00
2026-02-16 00:00:00
2026-02-17 00:00:00
nan
2026-02-19
2026-02-20 00:00:00
2026-02-23 00:00:00
2026-02-25 00:00:00
2026-02-26
2026-02-26 00:00:00
2026-02-27
2026-03-05
2026-03-05 00:00:00
2026-03-06 00:00:00
06-mar-2026
2026-03-07 00:00:00
2026-03-10 00:00:00
2026-03-12 00:00:00
12-mar-2026
2026-03-14
2026-03-15 00:00:00
15-mar-2026
2026-03-16 00:00:00
19-mar-2026
2026-03-20 00:00:00
20-mar-2026
2026-03-21
2026-03-22 00:00:00
2026-03-25 00:00:00
2026-03-26 00:00:00
2026-03-27 00:00:00
2026-04-01 00:00:00
2026-04-05 00:00:00
2026-04-10 00:00:00
2026-04-13
2026-04-20 00:00:00
2026-04-23 00:00:00
2026-04-26 00:00:00

Cliente

Irrigação Vale Forte
Grades Caruaru
Serralheria Capibaribe
Agro Estruturas São Francisco
Estaleiro Porto Novo
Calhas Olinda
nan
Estruturas Piedade
Construtora Boa Vista
Metalfer Agreste
Esquadrias Recife Antigo
Indústria Guararapes
Serralheria Alto da Sé

Cidade

Petrolina
Caruaru
recife
Recife
REC
Olinda
nan
Jaboatão dos Guararapes

Produto

Tubo galvanizado 2"
Barra chata 1"
Telha trapezoidal
Chapa de aço 3 mm
Perfil U enrijecido
Cantoneira 1/2"
nan

Valor (R$)

3260
3570
1940
4910
4500
1350
5360
3900
4040
5700
4400
4510
2410
R$ 630,00
nan
5160
2390
3920
3340
R$ 2.240,00
1260
4800
2980
5960
1590
R$ 2.140,00
R$ 5.480,00
440
4290
R$ 6.190,00
1220
2080
800
1650
5350
5040
930
410
1330
3950
5540
3800
R$ 4.960,00
1120
5890
5770
4470
950
1040
2440
3610

Remoção das linhas com valores "Nan"

In [55]:
antes = len(prata)
prata = prata.dropna()
logger(
    "Linhas totalmente vazias",
    "Removidas linhas sem nenhum campo preenchido",
    antes - len(prata),
    "Linhas parcialmente preenchidas foram preservadas para evitar excluir pedidos que ainda podem ser recuperados."
)

✔ Linhas totalmente vazias: 3 linha(s) afetada(s)

Remoção dos pedidos duplicados

In [56]:
antes = len(prata)
prata = prata.drop_duplicates(subset="Pedido", keep="first")
logger(
    "Pedidos com número duplicado",
    "Mantido o primeiro registro de cada número de pedido",
    antes - len(prata),
    "Sem um campo de atualização ou outro critério, foi preservada a primeira ocorrência."
)

✔ Pedidos com número duplicado: 4 linha(s) afetada(s)

Padronização dos nomes das cidades

In [57]:
correctNames = {
    "recife": "Recife",
    "REC": "Recife",
}

prata["Cidade"].value_counts()

antes = prata["Cidade"].copy()

prata["Cidade"] = prata["Cidade"].replace(correctNames)

linhasCorrigidas = (antes != prata["Cidade"]).sum()
logger(
    "Cidade com grafias diferentes (recife/REC)",
    "Padronizadas as grafias para Recife",
    linhasCorrigidas,
    "Assumiu-se que recife e REC representam o município de Recife."
)

prata["Cidade"].value_counts()

✔ Cidade com grafias diferentes (recife/REC): 10 linha(s) afetada(s)

Cidade
Recife                     16
Caruaru                    11
Olinda                      9
Jaboatão dos Guararapes     9
Petrolina                   8
Name: count, dtype: int64

Padronização dos valores

In [58]:
antes = prata["Valor (R$)"].copy()

valorLimpo = (
    prata["Valor (R$)"]
    .astype("string")
    .str.replace(r"R\$\s*", "", regex=True)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .str.strip()
)

prata["Valor (R$)"] = pd.to_numeric(valorLimpo, errors="coerce")

linhasCorrigidas = (
    antes.notna() & (antes.astype("string") != prata["Valor (R$)"].astype("string"))
).sum()

logger(
    "Valores despadronizados",
    "Convertidos para números decimais",
    linhasCorrigidas,
    "Valores no padrão brasileiro foram interpretados com ponto como separador de milhar e vírgula como separador decimal."
)

✔ Valores despadronizados: 53 linha(s) afetada(s)

Padronização das datas

In [59]:
meses = {
    "jan": "01", "fev": "02", "mar": "03", "abr": "04",
    "mai": "05", "jun": "06", "jul": "07", "ago": "08",
    "set": "09", "out": "10", "nov": "11", "dez": "12",
}

antes = prata["Data"].copy()

datas = (
    prata["Data"]
    .astype("string")
    .str.strip()
    .str.lower()
)

for mes, numero in meses.items():
    datas = datas.str.replace(mes, numero, regex=False)

datas_convertidas = pd.Series(pd.NaT, index=datas.index, dtype="datetime64[ns]")
for formato in ["%Y-%m-%d %H:%M:%S", "%Y-%m-%d",
                "%d-%m-%Y", "%d/%m/%Y", "%d/%m/%y"]:
    datas_convertidas = datas_convertidas.fillna(
        pd.to_datetime(datas, format=formato, errors="coerce")
    )

prata["Data"] = datas_convertidas.dt.strftime("%d/%m/%y").astype("string")
linhasConvertidas = (antes.notna() & prata["Data"].notna() & (antes.astype("string") != prata["Data"])).sum()

linhas_invalidas = (antes.notna() & prata["Data"].isna()).sum()

logger(
    "Datas em formatos diferentes",
    f"Padronizadas para dd/mm/aa: {linhasConvertidas}; inválidas para revisão: {linhas_invalidas}",
    linhasConvertidas,
    "Abreviações de meses em português foram convertidas para números; datas não interpretadas precisam de revisão."
)

prata[["Data"]]

✔ Datas em formatos diferentes: 53 linha(s) afetada(s)

        Data
0   01/01/26
1   02/01/26
2   06/01/26
3   07/01/26
4   16/01/26
5   27/01/26
6   01/02/26
7   04/02/26
8   06/02/26
9   07/02/26
10  13/02/26
11  15/02/26
12  16/02/26
13  17/02/26
15  19/02/26
16  20/02/26
17  23/02/26
18  25/02/26
19  26/02/26
20  26/02/26
21  27/02/26
22  05/03/26
24  05/03/26
25  06/03/26
26  06/03/26
27  07/03/26
28  10/03/26
29  12/03/26
30  12/03/26
32  12/03/26
35  14/03/26
36  14/03/26
37  15/03/26
38  15/03/26
39  16/03/26
40  16/03/26
41  19/03/26
42  20/03/26
43  20/03/26
44  20/03/26
45  21/03/26
46  22/03/26
47  25/03/26
48  26/03/26
49  27/03/26
50  01/04/26
52  05/04/26
53  10/04/26
54  13/04/26
55  20/04/26
56  23/04/26
57  23/04/26
58  26/04/26

# Ouro

In [60]:
base_ouro = prata.copy()
base_ouro["Mês"] = pd.to_datetime(base_ouro["Data"], format="%d/%m/%y", errors="raise").dt.month.map({
        1: "Janeiro", 2: "Fevereiro", 3: "Março", 4: "Abril",
        5: "Maio", 6: "Junho", 7: "Julho", 8: "Agosto",
        9: "Setembro", 10: "Outubro", 11: "Novembro", 12: "Dezembro"
    })
ordem_meses = ["Janeiro", "Fevereiro", "Março", "Abril",
                   "Maio", "Junho", "Julho", "Agosto", "Setembro",
                   "Outubro", "Novembro", "Dezembro"]
ouro = base_ouro.pivot_table(
        index="Cidade", columns="Mês", values="Valor (R$)",
        aggfunc="sum", fill_value=0, margins=True, margins_name="Total"
    ).reindex(columns=ordem_meses + ["Total"], fill_value=0).reset_index()

# Exportação

In [61]:
colunas_log = [
    "O que encontrei",
    "O que fiz",
    "Linhas afetadas",
    "Justificativa (se houve dúvida)",
]
log_df = pd.DataFrame(logs, columns=colunas_log)

arquivo_saida = "data/pedidos_metalurgica_tratados.xlsx"
with pd.ExcelWriter(arquivo_saida, engine="openpyxl") as writer:
    bronze.to_excel(writer, sheet_name="Bronze", index=False)
    prata.to_excel(writer, sheet_name="Prata", index=False)
    ouro.to_excel(writer, sheet_name="Ouro", index=False)
    log_df.to_excel(writer, sheet_name="Log", index=False)
    
print(f"Arquivo salvo em: {arquivo_saida}")
log_df

Arquivo salvo em: data/pedidos_metalurgica_tratados.xlsx

,O que encontrei,O que fiz,Linhas afetadas,Justificativa (se houve dúvida)
0,Linhas totalmente vazias,Removidas linhas sem nenhum campo preenchido,3,Linhas parcialmente preenchidas foram preserva...
1,Pedidos com número duplicado,Mantido o primeiro registro de cada número de ...,4,"Sem um campo de atualização ou outro critério,..."
2,Cidade com grafias diferentes (recife/REC),Padronizadas as grafias para Recife,10,Assumiu-se que recife e REC representam o muni...
3,Valores despadronizados,Convertidos para números decimais,53,Valores no padrão brasileiro foram interpretad...
4,Datas em formatos diferentes,Padronizadas para dd/mm/aa: 53; inválidas para...,53,Abreviações de meses em português foram conver...

In [62]:
vendas_mensais = prata.copy()

vendas_mensais["Mês"] = pd.to_datetime(vendas_mensais["Data"], format="%d/%m/%y").dt.to_period("M")

faturamento_mensal = vendas_mensais.groupby(["Cidade", "Mês"])["Valor (R$)"].sum()

cidade_campea, mes_campeao = faturamento_mensal.idxmax()

valor_campeao = faturamento_mensal.loc[(cidade_campea, mes_campeao)]


nomes_meses = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
               "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]

def formatar_reais(valor):
    return (f"R$ {valor:,.2f}"
            .replace(",", "_")
            .replace(".", ",")
            .replace("_", "."))

print(f"A cidade que mais comprou em um único mês foi {cidade_campea}, em {nomes_meses[mes_campeao.month - 1]} de {mes_campeao.year}, com {formatar_reais(valor_campeao)}.")

A cidade que mais comprou em um único mês foi Recife, em Março de 2026, com R$ 29.730,00.